import pandas as pd

split_time = pd.to_datetime(1730419200000, unit="ms") # Nov, Dec as test set

factor_cols = [
    # "open_time",
    "open",
    "high",
    "low",
    "close",
    "volume",
    # "close_time",
    "quote_volume",
    "count",
    "taker_buy_volume",
    "taker_buy_quote_volume",
    "ignore",
    "macd",
    "macd_signal",
    "macd_diff",
    "rsi",
    "ema_20",
    "sma_20",
    "bb_bbm",
    "bb_bbh",
    "bb_bbl",
    "adx",
    "stoch_k",
    "stoch_d",
    "cci",
    "roc",
    "obv",
    "mfi",
    "vwap",
    "atr",
    "donchian_high",
    "donchian_low",
    "williams_r",
]
